CREATE TABLE "IoT_schema".dai1_3k_1min
(
    "timestamp" timestamp with time zone NOT NULL,
    "GT行" integer,
    "3K行" integer,
    "出荷" integer,
    "当出" integer,
    "検品" integer,
    "XB前" integer,
    "完了" integer,
    "XB前2" integer,
    "完了2" integer,
    "3M前_先染" integer,
    "3M前_後染" integer,
    "仕上_先染" integer,
    "仕上_後染" integer,
    "3X_先染" integer,
    "3X_後染" integer,
    "3M_先染" integer,
    "3M_後染" integer,
    "7M_先染" integer,
    "7M_後染" integer,
    "2X_先染" integer,
    "2X_後染" integer,
    "3MM_先染" integer,
    "3MM_後染" integer,
    "7MM_先染" integer,
    "7MM_後染" integer,
    "日化_先染" integer,
    "日化_後染" integer,
    "風合_先染" integer,
    "風合_後染" integer,
    "物性_先染" integer,
    "物性_後染" integer,
    "他_先染" integer,
    "他_後染" integer,
    "GT残_先染" integer,
    "GT残_後染" integer,
    "GT残_ニット_先染" integer,
    "GT残_ニット_後染" integer,
    "GT残_織物_先染" integer,
    "GT残_織物_後染" integer,
    "3K_先染" integer,
    "3K_後染" integer,
    "3K_ニット_先染" integer,
    "3K_ニット_後染" integer,
    "3K_織物_先染" integer,
    "3K_織物_後染" integer,
    PRIMARY KEY ("timestamp")
);

ALTER TABLE IF EXISTS "IoT_schema".dai1_3k_1min
    OWNER to pgadmin;